import logging
bot_logger = logging.getLogger("bot_logger")
aiogram_logger = logging.getLogger("aiogram")
bot_logger.setLevel(logging.INFO)
aiogram_logger.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
file_handler = logging.FileHandler('bot.log')
file_handler.setLevel(logging.INFO)
file_handler.setFormatter(formatter)
console_handler = logging.StreamHandler()
console_handler.setLevel(logging.INFO)
console_handler.setFormatter(formatter)
bot_logger.addHandler(file_handler)
bot_logger.addHandler(console_handler)
aiogram_logger.addHandler(file_handler)
aiogram_logger.addHandler(console_handler)